server:
  port: ${BILGE_SERVER_PORT}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://192.168.1.1:5555/Ornek
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true